# Generated by Django 5.2.9 on 2025-12-09 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_poll_is_shareholder_vote_projet_coordinates_3d_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shares', models.IntegerField(help_text="Nombre d'actions détenues")),
                ('amount_invested', models.DecimalField(decimal_places=2, help_text='Montant investi (€)', max_digits=12)),
                ('subscription_bulletin', models.FileField(blank=True, help_text='Bulletin de souscription signé (PDF)', null=True, upload_to='secure/legal/')),
                ('is_signed', models.BooleanField(default=False, help_text='Bulletin signé et validé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shareholdings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shareholders', to='core.projet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'investor')},
            },
        ),
    ]
