# Generated by Django 5.2.9 on 2025-12-09 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_educationalcontent_audio_source_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Solde disponible (€)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Dépôt (Stripe -> Wallet)'), ('PLEDGE_DONATION', 'Don (Cantonné)'), ('PLEDGE_EQUITY', 'Investissement (Cantonné)'), ('REFUND', 'Remboursement'), ('RELEASE', 'Libération des fonds'), ('COMMISSION', 'Commission EGOEJO')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(blank=True, help_text='Clé unique pour éviter de rejouer la même transaction (dédoublonnage)', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='core.projet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.userwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('LOCKED', 'Verrouillé (Cantonné)'), ('RELEASED', 'Libéré'), ('REFUNDED', 'Remboursé')], default='LOCKED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_contracts', to='core.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_contracts', to=settings.AUTH_USER_MODEL)),
                ('pledge_transaction', models.OneToOneField(help_text='Transaction de cantonnement associée', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_contract', to='finance.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='finance_wal_idempot_c40127_idx'),
        ),
    ]
