# Generated by Django 5.2.9 on 2025-12-10 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt (Stripe -> Wallet)'), ('PLEDGE_DONATION', 'Don (Cantonné)'), ('PLEDGE_EQUITY', 'Investissement (Cantonné)'), ('REFUND', 'Remboursement'), ('RELEASE', 'Libération des fonds'), ('COMMISSION', 'Commission EGOEJO'), ('POCKET_TRANSFER', 'Transfert vers Pocket')], max_length=20),
        ),
        migrations.CreateModel(
            name='WalletPocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de la pocket (ex: 'Dons Environnement', 'Réserve Investissement')", max_length=100)),
                ('pocket_type', models.CharField(choices=[('DONATION', 'Dons'), ('INVESTMENT_RESERVE', "Réserve d'investissement")], help_text='Type de pocket', max_length=20)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Pourcentage d'allocation automatique (0-100)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant objectif (optionnel)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant actuel dans la pocket', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(help_text='Wallet parent', on_delete=django.db.models.deletion.CASCADE, related_name='pockets', to='finance.userwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('wallet', 'name')},
            },
        ),
    ]
