# Generated by Django 5.2.8 on 2025-12-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowcontract',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Verrouillé (Cantonné)'), ('RELEASED', 'Libéré'), ('REFUNDED', 'Remboursé')], db_index=True, default='LOCKED', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Clé unique pour éviter de rejouer la même transaction (dédoublonnage)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt (Stripe -> Wallet)'), ('PLEDGE_DONATION', 'Don (Cantonné)'), ('PLEDGE_EQUITY', 'Investissement (Cantonné)'), ('REFUND', 'Remboursement'), ('RELEASE', 'Libération des fonds'), ('COMMISSION', 'Commission EGOEJO'), ('POCKET_TRANSFER', 'Transfert vers Pocket')], db_index=True, max_length=20),
        ),
    ]
