# Generated by Django 5.2.8 on 2025-11-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collaboration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuEducatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_contenu', models.CharField(choices=[('podcast', 'Podcast'), ('pdf', 'PDF'), ('video', 'Vidéo')], max_length=20)),
                ('fichier', models.FileField(upload_to='contenus_educatifs/')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé par admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenus_educatifs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenu éducatif',
                'verbose_name_plural': 'Contenus éducatifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=2000)),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé par admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_contenus', to=settings.AUTH_USER_MODEL)),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.contenueducatif')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.contenueducatif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_contenus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['-created_at'],
                'unique_together': {('contenu', 'user')},
            },
        ),
    ]
