# Generated by Django 4.2.26 on 2025-11-18 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_contenueducatif_commentaire_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('help_type', models.CharField(choices=[('financier', 'Financier'), ('humain', 'Humain / accompagnement'), ('materiel', 'Matériel'), ('autre', 'Autre')], default='financier', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], default='medium', max_length=10)),
                ('is_linked_to_project', models.BooleanField(default=False, help_text='La demande est-elle liée à un projet EGOEJO ?')),
                ('anonymity', models.CharField(choices=[('pseudo', 'Afficher le pseudo'), ('team_only', "Visible seulement pour l'équipe EGOEJO")], default='pseudo', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouvelle demande'), ('in_review', "En cours d'étude"), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('archived', 'Archivée')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Projet lié (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to='core.projet')),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur connecté à l'origine de la demande (peut être nul).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
