# Generated by Django 4.2.26 on 2025-11-19 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_types', models.JSONField(blank=True, default=list, help_text="Liste des types d'aide proposés (financier, temps, compétences, matériel).")),
                ('domains', models.JSONField(blank=True, default=list, help_text='Liste des domaines (éducation, santé, agriculture, etc.).')),
                ('availability', models.TextField(blank=True, help_text='Disponibilités décrites par la personne (jours, horaires, fréquence).')),
                ('scope', models.CharField(choices=[('local', 'Principalement local / proche'), ('international', 'Ouvert à l’international'), ('both', 'Les deux')], default='both', max_length=20)),
                ('anonymity', models.CharField(choices=[('pseudo', 'Afficher le pseudo'), ('team_only', "Visible seulement pour l'équipe EGOEJO")], default='pseudo', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Message complémentaire sur la manière d’aider.')),
                ('status', models.CharField(choices=[('new', 'Nouvel engagement'), ('in_review', "En cours d'étude"), ('active', 'Actif'), ('archived', 'Archivé')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur connecté à l'origine de l'engagement (peut être nul).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
