# Generated by Django 4.2.26 on 2025-11-19 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, help_text='Nom/pseudo affiché pour ce commentaire si différent du profil.', max_length=255)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('podcast', 'Podcast'), ('video', 'Vidéo'), ('pdf', 'PDF / Rapport'), ('article', 'Article'), ('poeme', 'Poème'), ('chanson', 'Chanson'), ('autre', 'Autre')], default='article', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'Publié'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('anonymous_display_name', models.CharField(blank=True, help_text="Nom/pseudo à afficher si l'auteur veut rester discret.", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, help_text='Fichier PDF, audio, etc. (optionnel si lien externe).', null=True, upload_to='educational_contents/')),
                ('external_url', models.URLField(blank=True, help_text='Lien externe (YouTube, Spotify, site…) si pas de fichier uploadé.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Auteur du contenu (peut être nul si anonyme).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_contents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Projet EGOEJO lié (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_contents', to='core.projet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contenueducatif',
            name='auteur',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='ContenuEducatif',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='contentlike',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.educationalcontent'),
        ),
        migrations.AddField(
            model_name='contentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.educationalcontent'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contentlike',
            unique_together={('user', 'content')},
        ),
    ]
