# Generated by Django 4.2.26 on 2025-11-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contentcomment_contentlike_educationalcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='help_request',
            field=models.ForeignKey(blank=True, help_text="Demande d'aide / projet lié à cet engagement (optionnel).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='core.helprequest'),
        ),
    ]
