# Generated by Django 5.2.9 on 2025-12-08 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_engagement_help_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('performance', 'Performance'), ('api', 'API')], max_length=20)),
                ('message', models.TextField(help_text="Message d'alerte")),
                ('url', models.URLField(blank=True, help_text='URL de la page', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées supplémentaires (contexte, etc.)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False, help_text='Alerte résolue')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur (si authentifié)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_alert',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='monitoring__timesta_6f34e3_idx'), models.Index(fields=['level', 'resolved', 'timestamp'], name='monitoring__level_b1090a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('LCP', 'Largest Contentful Paint'), ('FID', 'First Input Delay'), ('CLS', 'Cumulative Layout Shift'), ('TTFB', 'Time to First Byte'), ('FCP', 'First Contentful Paint'), ('PageLoad', 'Page Load Time'), ('DOMContentLoaded', 'DOM Content Loaded'), ('API_Duration', 'API Request Duration'), ('Custom', 'Custom Metric')], max_length=50)),
                ('value', models.FloatField(help_text='Valeur de la métrique')),
                ('url', models.URLField(blank=True, help_text='URL de la page', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées supplémentaires (endpoint, etc.)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur (si authentifié)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_performance_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'metric_type'], name='monitoring__timesta_e9a6cc_idx'), models.Index(fields=['metric_type', 'timestamp'], name='monitoring__metric__b44104_idx')],
            },
        ),
    ]
