# Generated by Django 5.2.9 on 2025-12-08 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_monitoringalert_performancemetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='category',
            field=models.CharField(choices=[('ressources', 'Ressources'), ('guides', 'Guides'), ('videos', 'Vidéos'), ('racines-philosophie', 'Racines & Philosophie'), ('autres', 'Autres')], default='autres', help_text='Catégorie du contenu (ex: Racines & Philosophie pour Steiner, Biodynamie)', max_length=50),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags comme 'Steiner', 'Biodynamie', etc."),
        ),
        migrations.CreateModel(
            name='ImpactDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, help_text='Total des contributions en euros', max_digits=10)),
                ('projects_supported', models.IntegerField(default=0, help_text='Nombre de projets soutenus')),
                ('cagnottes_contributed', models.IntegerField(default=0, help_text="Nombre de cagnottes auxquelles l'utilisateur a contribué")),
                ('intentions_submitted', models.IntegerField(default=0, help_text="Nombre d'intentions soumises")),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour des métriques')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tableau de bord d'impact",
                'verbose_name_plural': "Tableaux de bord d'impact",
                'db_table': 'impact_dashboard',
            },
        ),
    ]
