# Generated by Django 5.2.9 on 2025-12-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_to_pgvector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-created_at']},
        ),
    ]
