# Generated by Django 5.2.9 on 2025-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_audio_file_and_coordinates_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_shareholder_vote',
            field=models.BooleanField(default=False, help_text="Vote réservé aux actionnaires (V2.0) - Pondération par nombre d'actions"),
        ),
        migrations.AddField(
            model_name='projet',
            name='coordinates_3d',
            field=models.JSONField(blank=True, help_text='Coordonnées 3D (x, y, z) pour visualisation Mycélium Numérique', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='donation_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Objectif de dons (€)', max_digits=12),
        ),
        migrations.AddField(
            model_name='projet',
            name='funding_type',
            field=models.CharField(choices=[('DONATION', 'Don Philanthropique'), ('EQUITY', 'Investissement (Actions)'), ('HYBRID', 'Mixte (Blended Finance)')], default='DONATION', help_text='Type de financement (DONATION par défaut, EQUITY/HYBRID dormant V2.0)', max_length=10),
        ),
        migrations.AddField(
            model_name='projet',
            name='investment_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Objectif d'investissement (€) - Dormant V2.0", max_digits=12),
        ),
        migrations.AddField(
            model_name='projet',
            name='share_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix de l'action (€) - Dormant V2.0", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='total_shares',
            field=models.IntegerField(blank=True, help_text="Nombre total d'actions - Dormant V2.0", null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='valuation_pre_money',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valorisation pré-money (€) - Dormant V2.0', max_digits=15, null=True),
        ),
    ]
