# Generated by Django 5.2.9 on 2025-12-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_poll_is_shareholder_vote_projet_coordinates_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='audio_source_hash',
            field=models.CharField(blank=True, help_text='SHA-256 du texte source utilisé pour le TTS (pour éviter les doublons).', max_length=64),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='embedding_source_hash',
            field=models.CharField(blank=True, help_text="SHA-256 du texte source utilisé pour l'embedding (pour éviter les doublons).", max_length=64),
        ),
    ]
