# Generated by Django 5.2.9 on 2025-12-10 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_educationalcontent_audio_source_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='thread_type',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('PROJECT', 'Projet'), ('SUPPORT_CONCIERGE', 'Support Concierge')], default='GENERAL', help_text='Type de thread (GENERAL, PROJECT, SUPPORT_CONCIERGE)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('thread_type', 'SUPPORT_CONCIERGE')), fields=('created_by', 'thread_type'), name='unique_support_concierge_per_user'),
        ),
    ]
