# Generated by Django 5.2.9 on 2025-12-11 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_thread_type_support_concierge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SakaWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='Solde SAKA disponible (grains)')),
                ('total_harvested', models.PositiveIntegerField(default=0, help_text='Total de grains SAKA jamais récoltés')),
                ('total_planted', models.PositiveIntegerField(default=0, help_text='Total de grains SAKA jamais plantés (engagés)')),
                ('total_composted', models.PositiveIntegerField(default=0, help_text='Total de grains SAKA compostés (retournés au Silo)')),
                ('last_activity_date', models.DateTimeField(blank=True, help_text='Date de la dernière activité SAKA', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du portefeuille')),
                ('user', models.OneToOneField(help_text='Utilisateur propriétaire du portefeuille SAKA', on_delete=django.db.models.deletion.CASCADE, related_name='saka_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille SAKA',
                'verbose_name_plural': 'Portefeuilles SAKA',
                'ordering': ['-balance', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SakaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('EARN', 'Récolte - Grains gagnés'), ('SPEND', 'Dépense - Grains utilisés')], help_text='Direction de la transaction (EARN ou SPEND)', max_length=5)),
                ('amount', models.PositiveIntegerField(help_text='Nombre de grains SAKA')),
                ('reason', models.CharField(help_text="Raison de la transaction (ex: 'content_read', 'poll_vote', 'invite_accepted')", max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées supplémentaires (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la transaction')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='saka_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction SAKA',
                'verbose_name_plural': 'Transactions SAKA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_sakatr_user_id_83622d_idx'), models.Index(fields=['direction', '-created_at'], name='core_sakatr_directi_443600_idx'), models.Index(fields=['reason', '-created_at'], name='core_sakatr_reason_378b8e_idx')],
            },
        ),
    ]
