# Generated by Django 5.2.9 on 2025-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_saka_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollballot',
            name='saka_spent',
            field=models.PositiveIntegerField(default=0, help_text='SAKA plantés pour ce vote (Phase 2 : Vote quadratique fertilisé)'),
        ),
        migrations.AddField(
            model_name='pollballot',
            name='weight',
            field=models.FloatField(blank=True, help_text='Poids calculé du vote (sqrt(intensity) * multiplier SAKA)', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='saka_score',
            field=models.PositiveIntegerField(default=0, help_text='Score de soutien SAKA (visibilité organique) - Phase 2'),
        ),
        migrations.AddField(
            model_name='projet',
            name='saka_supporters_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de membres ayant boosté ce projet avec SAKA - Phase 2'),
        ),
    ]
