# Generated by Django 5.2.9 on 2025-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_saka_phase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SakaSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.PositiveIntegerField(default=0, help_text='Solde total actuel du Silo Commun (grains compostés disponibles)')),
                ('total_composted', models.PositiveIntegerField(default=0, help_text='Total de grains jamais compostés dans le Silo (cumul historique)')),
                ('total_cycles', models.PositiveIntegerField(default=0, help_text='Nombre de cycles de compostage exécutés')),
                ('last_compost_at', models.DateTimeField(blank=True, help_text='Date du dernier cycle de compostage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du Silo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Silo Commun SAKA',
                'verbose_name_plural': 'Silos Communs SAKA',
            },
        ),
    ]
