# Generated by Django 5.2.9 on 2025-12-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_saka_silo_phase3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SakaCompostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Date de début du cycle de compostage')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Date de fin du cycle de compostage', null=True)),
                ('dry_run', models.BooleanField(default=False, help_text='Si True, cycle de simulation (aucune écriture)')),
                ('wallets_affected', models.PositiveIntegerField(default=0, help_text='Nombre de wallets affectés par ce cycle')),
                ('total_composted', models.PositiveIntegerField(default=0, help_text='Total de grains SAKA compostés dans ce cycle')),
                ('inactivity_days', models.PositiveIntegerField(default=0, help_text="Nombre de jours d'inactivité requis pour être éligible")),
                ('rate', models.FloatField(default=0.0, help_text='Taux de compostage (ex: 0.1 = 10%)')),
                ('min_balance', models.PositiveIntegerField(default=0, help_text='Balance minimum requise pour être éligible')),
                ('min_amount', models.PositiveIntegerField(default=0, help_text='Montant minimum à composter par wallet')),
                ('source', models.CharField(default='celery', help_text="Source du cycle (ex: 'celery', 'admin', 'management_command')", max_length=32)),
            ],
            options={
                'verbose_name': 'Log de Compostage SAKA',
                'verbose_name_plural': 'Logs de Compostage SAKA',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='core_sakaco_started_625e12_idx'), models.Index(fields=['dry_run', '-started_at'], name='core_sakaco_dry_run_c5460a_idx'), models.Index(fields=['source', '-started_at'], name='core_sakaco_source_bbb3d1_idx')],
            },
        ),
    ]
