# Generated by Django 5.2.9 on 2025-12-14 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_saka_compost_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SakaProjectSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_saka_spent', models.PositiveIntegerField(default=0, help_text='Total de SAKA dépensé par cet utilisateur pour ce projet')),
                ('first_boost_at', models.DateTimeField(auto_now_add=True, help_text='Date du premier boost')),
                ('last_boost_at', models.DateTimeField(auto_now=True, help_text='Date du dernier boost')),
                ('project', models.ForeignKey(help_text='Projet boosté', on_delete=django.db.models.deletion.CASCADE, related_name='saka_supports', to='core.projet')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a boosté le projet', on_delete=django.db.models.deletion.CASCADE, related_name='saka_project_supports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support SAKA Projet',
                'verbose_name_plural': 'Supports SAKA Projets',
                'indexes': [models.Index(fields=['project', '-last_boost_at'], name='core_sakapr_project_c5c404_idx'), models.Index(fields=['user', '-last_boost_at'], name='core_sakapr_user_id_8a98da_idx')],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
