# Generated by Django 5.2.8 on 2025-12-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_saka_project_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImpact4P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_score', models.DecimalField(decimal_places=2, default=0, help_text='P1 : Performance financière (euros mobilisés)', max_digits=12)),
                ('saka_score', models.PositiveIntegerField(default=0, help_text='P2 : Performance vivante (SAKA mobilisé pour ce projet)')),
                ('social_score', models.PositiveIntegerField(default=0, help_text="P3 : Performance sociale/écologique (score d'impact agrégé)")),
                ('purpose_score', models.PositiveIntegerField(default=0, help_text='P4 : Purpose / Sens (indicateur qualitatif)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour des scores 4P')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('project', models.OneToOneField(help_text='Projet associé', on_delete=django.db.models.deletion.CASCADE, related_name='impact_4p', to='core.projet')),
            ],
            options={
                'verbose_name': 'Score 4P Projet',
                'verbose_name_plural': 'Scores 4P Projets',
                'db_table': 'project_impact_4p',
                'ordering': ['-updated_at'],
            },
        ),
    ]
