# Generated by Django 5.2.8 on 2025-12-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_projectimpact4p'),
    ]

    operations = [
        migrations.CreateModel(
            name='SakaCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom du cycle (ex: 'Saison 2026 / 1')", max_length=128)),
                ('start_date', models.DateField(help_text='Date de début du cycle')),
                ('end_date', models.DateField(help_text='Date de fin du cycle')),
                ('is_active', models.BooleanField(default=False, help_text='Si True, ce cycle est actuellement actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Cycle SAKA',
                'verbose_name_plural': 'Cycles SAKA',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', '-start_date'], name='core_sakacy_is_acti_c6f5bb_idx'), models.Index(fields=['start_date', 'end_date'], name='core_sakacy_start_d_9a2427_idx')],
            },
        ),
        migrations.AddField(
            model_name='sakacompostlog',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Cycle SAKA associé (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compost_logs', to='core.sakacycle'),
        ),
    ]
