# Generated by Django 5.2.9 on 2025-12-16 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sakacycle_sakacompostlog_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la communauté', max_length=255)),
                ('slug', models.SlugField(help_text='Identifiant unique URL-friendly (auto-généré si vide)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la communauté', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si False, la communauté est désactivée')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
                ('members', models.ManyToManyField(blank=True, help_text='Membres de la communauté', related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communauté',
                'verbose_name_plural': 'Communautés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='community',
            field=models.ForeignKey(blank=True, help_text='Communauté associée (optionnel, pour subsidiarité future)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.community'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug'], name='core_commun_slug_4749d8_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['is_active', '-created_at'], name='core_commun_is_acti_5bf868_idx'),
        ),
    ]
