# Generated by Django 5.2.8 on 2025-12-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_active_oracles_to_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimpact4p',
            name='purpose_score',
            field=models.PositiveIntegerField(default=0, help_text='P4 : Purpose / Sens (PROXY V1 - indicateur interne simplifié, non académique)'),
        ),
        migrations.AlterField(
            model_name='projectimpact4p',
            name='social_score',
            field=models.PositiveIntegerField(default=0, help_text="P3 : Performance sociale/écologique (PROXY V1 - score d'impact interne simplifié, non académique)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='active_oracles',
            field=models.JSONField(blank=True, default=list, help_text="Liste des identifiants d'oracles d'impact actifs pour ce projet (ex: ['co2_avoided', 'social_impact']). Préparation de la tuyauterie pour ingérer des données externes vérifiées."),
        ),
    ]
