# Generated by Django 5.2.9 on 2025-12-29 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_projectimpact4p_purpose_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur ayant modifié ce contenu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Date de publication du contenu.', null=True),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a publié ce contenu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'Publié'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='pending', max_length=20),
        ),
    ]
