# Generated by Django 5.2.9 on 2026-01-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_transaction_type_to_sakatransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Raison du signalement (optionnel)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examiné'), ('dismissed', 'Rejeté')], default='pending', help_text='Statut du signalement', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text="Date d'examen du signalement", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='criticalalertevent',
            new_name='core_critic_created_231ab2_idx',
            old_name='core_criti_created_idx',
        ),
        migrations.RenameIndex(
            model_name='criticalalertevent',
            new_name='core_critic_event_t_de786a_idx',
            old_name='core_criti_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='criticalalertevent',
            new_name='core_critic_channel_8fee79_idx',
            old_name='core_criti_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='criticalalertevent',
            new_name='core_critic_severit_f85d1c_idx',
            old_name='core_criti_severity_idx',
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='message',
            field=models.ForeignKey(help_text='Message signalé', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='reporter',
            field=models.ForeignKey(help_text='Utilisateur qui a signalé le message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Modérateur qui a examiné le signalement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessagereport',
            unique_together={('message', 'reporter')},
        ),
    ]
